# Generated by Django 2.2.8 on 2019-12-14 08:51

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
