# Generated by Django 2.2.8 on 2019-12-15 14:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='caption1',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='caption2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='caption3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
