# Generated by Django 2.2.8 on 2019-12-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0006_auto_20191215_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='caption1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='caption3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
